### ISSUE TITLE
Don't make rosdep "continue on errors"

### ISSUE THREAD

**Issue by gavanderhoorn** [sam-xl/abb_robot_driver_state_machine#2]
The current setup instructions invoke `rosdep` with the `-r` option:

https://github.com/sam-xl/abb_robot_driver_state_machine/blob/5dcd5f51c3f7c549d5e174eec71566822db172f3/README.md?plain=1#L69-L71

This option makes `rosdep`

> Continue installing despite errors.

as `rosdep` is responsible for installing required dependencies, there doesn't appear to be any point in asking it to continue if it couldn't do that for whatever reason. Failing early while setting up the development environment would be much better.

Suggestion: remove `-r` from the `rosdep` invocation.

**Comment by dave992** [comment]
Makes sense indeed for the install instructions, thanks for making the PR. I'll merge it in.
